# Generated by Django 4.2.6 on 2023-11-01 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='cotent',
            new_name='content',
        ),
    ]
